### ISSUE TITLE
Version tag for rails-assets

### ISSUE THREAD

**Issue by mlangens** [formly-js/angular-formly-templates-foundation#5]
Hello,

I went to convert this repo on rails-assets.org and I got a "no version" error. Can you tag a version in this repo?

**Comment by kentcdodds** [comment]
This repo is not ready for release, so it doesn't have a version yet. What are you trying to do? I've never heard of rails-assets.org...

**Comment by mlangens** [comment]
rails-assets is an automated gem packager for bower projects; helps with versioning of vendor assets within the Rails asset pipeline. Any possibility of a version with a -beta.x suffix?

**Comment by kentcdodds** [comment]
Done. You have a `1.0.0-beta.1` release. Good luck :+1:

**Comment by mlangens** [comment]
thank you!
