### ISSUE TITLE
Update to apiCheck dependency giving deprecation warnings

### ISSUE THREAD

**Issue by nrcrabbe** [formly-js/angular-formly-templates-foundation#6]
Using apiCheck as an object has been deprecated (see: https://github.com/formly-js/angular-formly/issues/334). angular-formly-templates-foundation/src/types/\* still use apiCheck as an object.

**Comment by yonglinzhong** [comment]
Having the same issue here.

Error: [$injector:modulerr] Failed to instantiate module formlyFoundation due to:
Error: angular-formly: formlyConfig.setWrapper apiCheck failed! `apiCheck` at `Argument 1/value` must be `Function`

**Comment by Epotignano** [comment]
There is any solution for this?

**Comment by kentcdodds** [comment]
ping @httpJunkie

**Comment by kentcdodds** [comment]
Until this gets resolved, you can [disable `api-check`](http://angular-formly.com/#/example/other/production-tips). Definitely not preferable during development though :-(

**Comment by johnykov** [comment]
I love formly, I've been workin with it with compilation of boostrap and it simplified my work!
This time I need to use it with foundation and have this issue, and for the moment I've disabled api-check. Would there be any fix on this? :)

**Comment by kentcdodds** [comment]
Hi there! I'm having trouble building the project right now. I'm afraid I don't have any time to fix this. The code has been fixed, we just need to work out why the project wont build and then I can release. If you need this, please [makeapullrequest.com](http://makeapullrequest.com).

This is what I get when I try to run the build:

```
~/Developer/angular-formly-templates-foundation (master)
👽  $ npm run build

> angular-formly-templates-foundation@1.0.0-beta.2 build /Users/kdodds/Developer/angular-formly-templates-foundation
> npm run build:dist; npm run build:minify


> angular-formly-templates-foundation@1.0.0-beta.2 build:dist /Users/kdodds/Developer/angular-formly-templates-foundation
> webpack

building version 1.0.0-beta.2
Webpack config is in dev mode
Hash: 0bcb331bc609bd714836
Version: webpack 1.12.14
Time: 467ms
    + 1 hidden modules

ERROR in ./index.js
Module build failed: Error: "../index.js" is not in the SourceMap.
    at SourceMapConsumer_sourceContentFor [as sourceContentFor] (/Users/kdodds/Developer/angular-formly-templates-foundation/node_modules/source-map/lib/source-map/source-map-consumer.js:697:15)
    at SourceMapGenerator.<anonymous> (/Users/kdodds/Developer/angular-formly-templates-foundation/node_modules/source-map/lib/source-map/source-map-generator.js:233:42)
    at Array.forEach (native)
    at SourceMapGenerator_applySourceMap [as applySourceMap] (/Users/kdodds/Developer/angular-formly-templates-foundation/node_modules/source-map/lib/source-map/source-map-generator.js:232:34)
    at Object.module.exports (/Users/kdodds/Developer/angular-formly-templates-foundation/node_modules/ng-annotate-loader/loader.js:20:17)

> angular-formly-templates-foundation@1.0.0-beta.2 build:minify /Users/kdodds/Developer/angular-formly-templates-foundation
> webpack --config webpack.config.minify.js

building version 1.0.0-beta.2
Webpack config is in dev mode
Webpack config is in prod mode
Hash: 10e9a67866b5ba420a5b
Version: webpack 1.12.14
Time: 464ms
    + 1 hidden modules

ERROR in ./index.js
Module build failed: Error: "../index.js" is not in the SourceMap.
    at SourceMapConsumer_sourceContentFor [as sourceContentFor] (/Users/kdodds/Developer/angular-formly-templates-foundation/node_modules/source-map/lib/source-map/source-map-consumer.js:697:15)
    at SourceMapGenerator.<anonymous> (/Users/kdodds/Developer/angular-formly-templates-foundation/node_modules/source-map/lib/source-map/source-map-generator.js:233:42)
    at Array.forEach (native)
    at SourceMapGenerator_applySourceMap [as applySourceMap] (/Users/kdodds/Developer/angular-formly-templates-foundation/node_modules/source-map/lib/source-map/source-map-generator.js:232:34)
    at Object.module.exports (/Users/kdodds/Developer/angular-formly-templates-foundation/node_modules/ng-annotate-loader/loader.js:20:17)
```

Good luck! :+1:

**Comment by nrcrabbe** [comment]
I've started looking into this, no joy yet. 

I see the same error signature referenced in the bootstrap repo: https://github.com/formly-js/angular-formly-templates-bootstrap/issues/14#issuecomment-143467754 which was resolved. From the conversation I can't pick up on what the solution was. @kentcdodds does this ring any bells with you?

**Comment by nrcrabbe** [comment]
Okay I'm running out of time to look at this. Here are my findings.

forked to here: https://github.com/nrcrabbe/angular-formly-templates-foundation/commit/fa03bc89c5e9f71cef54d8646756a60feba9f1df

had to add/update some dependencies, and there was a bug in checkbox.js.

It builds (and runs well on my dev website), but `npm run test` runs into two issues:
1. `ERROR in ./src/index.test.js
   Module not found: Error: Cannot resolve 'file' or 'directory' ./run/index.test in /home/nathan/projects/formly2/angular-formly-templates-foundation/src
   @ ./src/index.test.js 10:0-27`
   We are looking for a non-existent file.
2. `Uncaught TypeError: __webpack_require__(...) is not a function
   at /home/nathan/projects/formly2/angular-formly-templates-foundation/src/index.test.js:41590`
   Over my head...

I'm hoping I can pass the baton to someone here. This is my first dip into webpack so I'm a bit lost.

Cheers

**Comment by hanskoff** [comment]
I've bumped two dependencies and manage to build:
```
+    "ng-annotate": "^1.2.1",
+    "ng-annotate-loader": "0.1.0",
```
but tests doesn't pass :( I see:
```
ERROR in ./src/index.test.js
Module not found: Error: Cannot resolve 'file' or 'directory' ./run/index.test in /Users/jankowalski/3prty/angular-formly-templates-foundation/src
 @ ./src/index.test.js 10:0-27
webpack: bundle is now VALID.
26 02 2016 09:52:04.634:INFO [karma]: Delaying execution, these browsers are not ready: Chrome 48.0.2564 (Mac OS X 10.11.3)
Chrome 48.0.2564 (Mac OS X 10.11.3) ERROR
  Uncaught TypeError: __webpack_require__(...) is not a function
  at /Users/jankowalski/3prty/angular-formly-templates-foundation/src/index.test.js:41590
```
and when I look into `./src/index.test.js` I see it `require('./run/index.test');` and there is no such a file ;)
and the second error `Uncaught TypeError...` I suspect it is somehow related to babel6 issue https://github.com/webpack/webpack/issues/1685 ?

**Comment by johnykov** [comment]
ad 1. there is no tests: missing `require('./run/index.test');`
ad 2. I think it's related to babel6 changes and that `export default` issue
https://github.com/webpack/webpack/issues/1685
I've added to `package.json`:

```
  "babel": {
    "plugins": [
      "add-module-exports"
    ]
  },
```

and installed `babel-plugin-add-module-exports` to fix this issue but without a luck, as karma reports that error maybe there is something that needs to be changed in karma.config

**Comment by johnykov** [comment]
bumping dependencies to

```
+    "ng-annotate": "^1.2.1",
+    "ng-annotate-loader": "0.1.0",
```

makes build pass again

**Comment by kentcdodds** [comment]
Awesome, I'll release something now. Thanks for looking into this!

**Comment by kentcdodds** [comment]
Try `npm install angular-formly-templates-foundation@1.0.0-beta.3`

Please close this if that fixes your issues :+1:

**Comment by nrcrabbe** [comment]
All good now, thanks all.
